copy CxImageFull_vs%1.sln CxImageFull_vs%2.sln
copy .\CxImage\cximage_vs%1.vcxproj .\CxImage\cximage_vs%2.vcxproj
copy .\CxImage\cximage_vs%1.vcxproj.filters .\CxImage\cximage_vs%2.vcxproj.filters
copy .\CxImage\CxImageDLL\CxImageCrtDll_vs%1.vcxproj .\CxImage\CxImageDLL\CxImageCrtDll_vs%2.vcxproj
copy .\CxImage\CxImageDLL\CxImageCrtDll_vs%1.vcxproj.filters .\CxImage\CxImageDLL\CxImageCrtDll_vs%2.vcxproj.filters
copy .\CxImage\CxImageDLL\cximagemfcdll_vs%1.vcxproj .\CxImage\CxImageDLL\cximagemfcdll_vs%2.vcxproj
copy .\CxImage\CxImageDLL\cximagemfcdll_vs%1.vcxproj.filters .\CxImage\CxImageDLL\cximagemfcdll_vs%2.vcxproj.filters
copy .\demo\demo_vs%1.vcxproj .\demo\demo_vs%2.vcxproj
copy .\demo\demo_vs%1.vcxproj.filters .\demo\demo_vs%2.vcxproj.filters
copy .\demo\demodll_vs%1.vcxproj .\demo\demodll_vs%2.vcxproj
copy .\demo\demodll_vs%1.vcxproj.filters .\demo\demodll_vs%2.vcxproj.filters
copy .\jasper\jasper_vs%1.vcxproj .\jasper\jasper_vs%2.vcxproj
copy .\jasper\jasper_vs%1.vcxproj.filters .\jasper\jasper_vs%2.vcxproj.filters
copy .\jbig\jbig_vs%1.vcxproj .\jbig\jbig_vs%2.vcxproj
copy .\jbig\jbig_vs%1.vcxproj.filters .\jbig\jbig_vs%2.vcxproj.filters
copy .\jpeg\jpeg_vs%1.vcxproj .\jpeg\jpeg_vs%2.vcxproj
copy .\jpeg\jpeg_vs%1.vcxproj.filters .\jpeg\jpeg_vs%2.vcxproj.filters
copy .\libpsd\libpsd_vs%1.vcxproj .\libpsd\libpsd_vs%2.vcxproj
copy .\libpsd\libpsd_vs%1.vcxproj.filters .\libpsd\libpsd_vs%2.vcxproj.filters
copy .\mng\mng_vs%1.vcxproj .\mng\mng_vs%2.vcxproj
copy .\mng\mng_vs%1.vcxproj.filters .\mng\mng_vs%2.vcxproj.filters
copy .\png\png_vs%1.vcxproj .\png\png_vs%2.vcxproj
copy .\png\png_vs%1.vcxproj.filters .\png\png_vs%2.vcxproj.filters
copy .\raw\libdcr_vs%1.vcxproj .\raw\libdcr_vs%2.vcxproj
copy .\raw\libdcr_vs%1.vcxproj.filters .\raw\libdcr_vs%2.vcxproj.filters
copy .\tiff\tiff_vs%1.vcxproj .\tiff\tiff_vs%2.vcxproj
copy .\tiff\tiff_vs%1.vcxproj.filters .\tiff\tiff_vs%2.vcxproj.filters
copy .\zlib\zlib_vs%1.vcxproj .\zlib\zlib_vs%2.vcxproj
copy .\zlib\zlib_vs%1.vcxproj.filters .\zlib\zlib_vs%2.vcxproj.filters
